name = "natalie-winters"
compatibility_date = "2024-03-16"

[build]
command = "cd src/sites/main-natalie && npm install --legacy-peer-deps && npm run build && npx @cloudflare/next-on-pages@1"
output_directory = "dist"
base_directory = "."
pages_build_output_dir = "src/sites/main-natalie/.vercel/output/static"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"

# Configure edge runtime
compatibility_date = "2024-03-14"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "/*"
zone_name = "business.nataliegwinters.com"

[site]
bucket = "src/sites/main-natalie/.vercel/output/static"
entry-point = "workers-site"

# Required for Cloudflare Pages
[build.upload]
format = "service-worker"
dir = ".next"
main = ".next/worker.js"

# Enable caching
[cache]
caching = true
cache_everything = true
cache_by_device_type = true
browser_ttl = 30
edge_ttl = 1800

# Security headers
[headers]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Configure preview deployments
[env.preview]
name = "natalie-winters-preview"
workers_dev = true

# Configure production deployments
[env.production]
name = "natalie-winters"
workers_dev = true 