[build]
command = "npm run main:build"

[build.environment]
NODE_VERSION = "18"
SITE = "main"

# Configure edge runtime
compatibility_date = "2024-03-14"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "/*"
zone_name = "nataliegwinters.com"

[site]
bucket = "src/sites/main-natalie/.next"

# Required for Cloudflare Pages
[build.upload]
format = "service-worker"
dir = "src/sites/main-natalie/.next"
main = "src/sites/main-natalie/.next/worker.js"

# Specify the build output directory
pages_build_output_dir = "src/sites/main-natalie/.next" 