[build]
command = "npm run build"
pages_build_output_dir = ".next"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = ".next"

# Required for Cloudflare Pages
[build.upload]
format = "service-worker"
dir = ".next"
main = ".next/worker.js"

# Specify the build output directory
pages_build_output_dir = ".next" 