name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - natalie-winters-dev
  pull_request:
    branches:
      - main
      - natalie-winters-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci
          cd src/sites/main-natalie && npm ci
          cd ../biz-natalie && npm ci
          cd ../news-natalie && npm ci

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: natalie-winters
          directory: dist
          # Deploy to production only from main branch
          branch: ${{ github.ref == 'refs/heads/main' && 'main' || 'preview' }}
          wranglerVersion: '3' 